# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Yarn build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      
        with:
          cmd: --cwd ui install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd ui  build # will run `yarn build` command

      - uses: JamesIves/github-pages-deploy-action@4.1.4
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: ui/dist 
